// Generates src/components/icon-paths.ts from Material Symbols (outlined, weight 400).
// Why: shipping only the path data for the icons we use keeps the bundle tiny and works
// offline, with the exact glyphs from the mockups. To add an icon: append its name to
// ICONS below (use "name-fill" for the filled variant), then run `npm run icons`.
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'add', 'alarm', 'archive', 'arrow_back', 'bedtime', 'bolt', 'brightness_auto',
  'calendar_view_week', 'check', 'check_circle', 'check_circle-fill', 'chevron_left',
  'chevron_right', 'close', 'dark_mode', 'date_range', 'delete', 'directions_run',
  'drag_indicator', 'edit', 'edit_note', 'error', 'event_repeat', 'favorite', 'favorite-fill',
  'fitness_center', 'grid_view', 'light_mode', 'local_cafe',
  'local_fire_department', 'lock', 'logout', 'menu_book', 'nightlight', 'monitoring', 'monitoring-fill', 'autorenew', 'palette', 'pill',
  'psychology', 'restaurant', 'schedule', 'self_improvement', 'shield', 'skip_next',
  'sports_tennis', 'sync', 'timer', 'trending_down', 'trending_up', 'troubleshoot',
  'keyboard_arrow_up', 'keyboard_arrow_down', 'repeat', 'content_copy', 'playlist_add', 'shopping_cart', 'directions_car', 'group', 'star', 'star-fill', 'checklist', 'inbox', 'drag_pan', 'event', 'event_upcoming', 'download', 'info', 'unfold_more', 'verified', 'view_day', 'wb_sunny', 'work', 'workspace_premium',
];

const dir = 'node_modules/@material-symbols/svg-400/outlined';
const entries = ICONS.map((name) => {
  const svg = readFileSync(`${dir}/${name}.svg`, 'utf8');
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${name}: expected 1 path, got ${paths.length}`);
  return `  '${name}': '${paths[0]}',`;
});

writeFileSync(
  'src/components/icon-paths.ts',
  `// Generated by scripts/gen-icons.mjs. Do not edit by hand.\n` +
    `// Material Symbols Outlined, Apache License 2.0, viewBox "0 -960 960 960".\n` +
    `export const ICON_PATHS = {\n${entries.join('\n')}\n} as const;\n\n` +
    `export type IconName = keyof typeof ICON_PATHS;\n`,
);
console.log(`Wrote ${ICONS.length} icons.`);
